export const ERRORS = {
    RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
    PEER_CONNECTION_ERROR: "PEER_CONNECTION_ERROR",
    GENERATE_KEYS_ERROR: "GENERATE_KEYS_ERROR",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    INVALID_DATABASE_NAME: "INVALID_DATABASE_NAME",
    DATA_CORRUPTION_ERROR: "DATA_CORRUPTION_ERROR"
}
